# Generated by Django 4.1.7 on 2023-04-07 11:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentPropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_property_category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_type_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_title', models.CharField(max_length=255)),
                ('rent_image', models.ImageField(upload_to='rent_images')),
                ('rent_size', models.CharField(max_length=255)),
                ('rent_price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('rent_description', models.TextField()),
                ('rent_upload_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.district')),
                ('rent_property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.rentpropertycategory')),
                ('rent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.renttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rent_title'],
            },
        ),
        migrations.AddField(
            model_name='city',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_rent.district'),
        ),
    ]
