# Generated by Django 4.1.7 on 2023-04-15 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouAre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('you_are', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='rentproperty',
            old_name='rent_upload_date',
            new_name='upload_date',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='rent_size',
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='admin_area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='agent_company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='agent_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='balcony',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='confrence_room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='daily_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='extras',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='furnished',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='lease_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='monthly_rent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='num_of_bathrooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='num_of_rooms',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='number_of_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='number_of_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='property_acre',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='property_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='rent_size_in_squrefeet',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='type_of_soil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_price',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_rent.renttype'),
        ),
        migrations.CreateModel(
            name='RentTypeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reny_type_category', models.CharField(max_length=100)),
                ('rent_property_category', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='pro_rent.rentpropertycategory')),
            ],
        ),
        migrations.CreateModel(
            name='RentMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('sale_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.rentproperty')),
            ],
        ),
    ]
