# Generated by Django 4.2 on 2023-04-24 05:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0004_alter_district_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentmessages',
            name='date_and_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 4, 24, 5, 58, 28, 326177, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
