# Generated by Django 4.2 on 2023-05-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0005_rentmessages_date_and_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_image',
            field=models.ImageField(blank=True, default='media/rent_images/download_BwNpVvW.jpeg', null=True, upload_to='rent_images'),
        ),
    ]
