# Generated by Django 4.2.1 on 2023-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0010_basedsize_rentproperty_per_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproperty',
            name='daily_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='lease_rent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='monthly_rent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
