# Generated by Django 4.2.1 on 2023-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0012_alter_rentproperty_upload_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmessages',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
