# Generated by Django 4.2.1 on 2023-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0013_alter_rentmessages_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentproperty',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='rentproperty',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_image',
            field=models.ImageField(blank=True, help_text='sale images', null=True, upload_to='rent_images/', verbose_name='sale images'),
        ),
    ]
