# Generated by Django 4.2.1 on 2023-05-22 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0014_rentproperty_image1_rentproperty_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentproperty',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='rentproperty',
            name='image5',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='proprty_images_images')),
                ('rent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pro_rent.rentproperty')),
            ],
        ),
    ]
