# Generated by Django 4.2.1 on 2023-05-22 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0015_remove_rentproperty_image1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='MultipleImages',
        ),
    ]
