# Generated by Django 4.2.1 on 2023-05-22 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0017_rentmultipleimages_delete_multipleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentmultipleimages',
            name='images',
            field=models.ImageField(upload_to='proprty_images'),
        ),
        migrations.AlterField(
            model_name='rentmultipleimages',
            name='rent_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pro_rent.rentproperty'),
        ),
    ]
