# Generated by Django 4.2 on 2023-06-02 12:19

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_rent', '0018_alter_rentmultipleimages_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentproperty',
            name='rent_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
