# Generated by Django 4.1.7 on 2023-04-15 06:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_rent', '0002_youare_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rent_title', models.CharField(blank=True, max_length=255, null=True)),
                ('property_name', models.CharField(max_length=100, null=True)),
                ('agent_name', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_company', models.CharField(blank=True, max_length=100, null=True)),
                ('num_of_rooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('num_of_bathrooms', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('balcony', models.CharField(blank=True, max_length=100, null=True)),
                ('furnished', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_area', models.CharField(blank=True, max_length=100, null=True)),
                ('confrence_room', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_soil', models.CharField(blank=True, max_length=100, null=True)),
                ('extras', models.TextField(blank=True, null=True)),
                ('rent_image', models.ImageField(blank=True, null=True, upload_to='rent_images')),
                ('rent_size_in_squrefeet', models.IntegerField(blank=True, null=True)),
                ('property_acre', models.FloatField(blank=True, null=True)),
                ('rent_price', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('rent_description', models.TextField(blank=True, null=True)),
                ('approved', models.BooleanField(default=False)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.city')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.district')),
                ('rent_property_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_rent.rentpropertycategory')),
                ('reny_type_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_rent.renttypecategory')),
            ],
        ),
    ]
