# Generated by Django 4.1.7 on 2023-04-15 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_rent', '0003_rentmessages_user_rentproperty_reny_type_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro_sale', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='you_are',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_rent.youare'),
        ),
        migrations.AddField(
            model_name='salemessages',
            name='sale_property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_sale.sellproperty'),
        ),
        migrations.AddField(
            model_name='salemessages',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
