# Generated by Django 4.2 on 2023-05-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0003_salemessages_date_and_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rent_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='rent_image',
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='rent_image',
            field=models.ManyToManyField(to='pro_sale.image'),
        ),
    ]
