# Generated by Django 4.2 on 2023-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0004_image_remove_sellproperty_rent_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='rent_images',
            field=models.ManyToManyField(to='pro_sale.image'),
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='rent_image',
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='rent_image',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images'),
        ),
    ]
