# Generated by Django 4.2 on 2023-05-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0005_sellproperty_rent_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproperty',
            name='rent_images',
        ),
    ]
