# Generated by Django 4.2 on 2023-05-04 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0006_remove_sellproperty_rent_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
