# Generated by Django 4.2.1 on 2023-05-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0008_remove_salemessages_message_salemessages_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sellproperty',
            name='rent_image',
            field=models.ImageField(blank=True, help_text='rent_images', null=True, upload_to='rent_images/', verbose_name='rent_images'),
        ),
    ]
