# Generated by Django 4.2.1 on 2023-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0010_remove_sellproperty_image_height_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproperty',
            name='rent_image',
            field=models.ImageField(blank=True, help_text='rent images', null=True, upload_to='rent_images/', verbose_name='rent images'),
        ),
    ]
