# Generated by Django 4.2.1 on 2023-05-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0011_alter_sellproperty_rent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
    ]
