# Generated by Django 4.2.1 on 2023-05-15 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0012_sellproperty_image_height_sellproperty_image_width'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproperty',
            name='image_height',
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='image_width',
        ),
    ]
