# Generated by Django 4.2.1 on 2023-05-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0017_alter_sellproperty_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='number_of_beds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='number_of_persons',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
