# Generated by Django 4.2.1 on 2023-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0018_sellproperty_number_of_beds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salemessages',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
