# Generated by Django 4.2.1 on 2023-05-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0019_alter_salemessages_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellproperty',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
        migrations.AddField(
            model_name='sellproperty',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='rent_images/'),
        ),
    ]
