# Generated by Django 4.2.1 on 2023-05-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0020_sellproperty_image1_sellproperty_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellproperty',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='sellproperty',
            name='image5',
        ),
        migrations.AlterField(
            model_name='sellproperty',
            name='rent_image',
            field=models.ImageField(blank=True, help_text='rent images', null=True, upload_to='sell_images/', verbose_name='rent images'),
        ),
    ]
