# Generated by Django 4.2.1 on 2023-05-22 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pro_sale', '0021_remove_sellproperty_image1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleMultipleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='proprty_images')),
                ('sell_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='pro_sale.sellproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
