# Generated by Django 4.2.1 on 2023-05-25 18:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_sale', '0022_salemultipleimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellproperty',
            name='rent_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
